<Project Sdk="Microsoft.NET.Sdk.Razor">
	
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	
	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Markdig" Version="0.43.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0-rc.2.25502.107" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\..\MATTAR.LocalAi\MATTAR.LocalAi.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<Content Update="wwwroot\app.css">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\app.js">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Update="wwwroot\favicon.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>
	
</Project>