<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.11.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="6.0.0-beta.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\MATTAR.LocalAi\MATTAR.LocalAi.csproj" />
    <ProjectReference Include="..\..\src\providers\MATTAR.LocalAi.OnnxProvider.Abstractions\MATTAR.LocalAi.OnnxProvider.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\providers\MATTAR.LocalAi.OnnxProvider.Cpu\MATTAR.LocalAi.OnnxProvider.Cpu.csproj" />
    <ProjectReference Include="..\..\src\providers\MATTAR.LocalAi.OnnxProvider.Cuda\MATTAR.LocalAi.OnnxProvider.Cuda.csproj" />
    <ProjectReference Include="..\..\src\providers\MATTAR.LocalAi.OnnxProvider.DirectML\MATTAR.LocalAi.OnnxProvider.DirectML.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>
</Project>